receivers:
  otlp:
    protocols:
      grpc:
processors:
  batch:
exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"
  logging:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true


service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, jaeger ]
    metrics:
      receivers: [ otlp ]
      exporters: [ logging, prometheus ]
    logs:
      receivers: [ otlp ]
      exporters: [ logging ]
